Allow specific confined users to use kerberos authentication
fedora-selinux/selinux-policy pull request #1030
Opened 2022-01-28 12:54 UTC by Koncpa

**Commit 1**

 Allow confined users to read keytab file (klist)

Confined users need to use kerberos authentication.
For users like auditadm_t and secadm_t allow
read kerberos keytab file via interface
kerberos_read_keytab().

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2026598

**Commit 2**

 Allow confined users to write keys

Confined users need to use kerberos authentication
for NFS. Allow confined users to write gssd keys and
use tools like kinit, klist and kdestroy. Allow for
confined users like staff_t, admin types and user_t.

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2026598

2022-02-03 19:55 UTC, zpytela requested changes
Please also fix the confide_admindomain typo in the commit message.

2022-02-03 19:55 UTC, zpytela commented on policy/modules/system/userdomain.te
> +        kerberos_read_keytab(confined_admindomain)
This looks like space-formatted.

2022-02-04 11:13 UTC, Koncpa commented
> Please also fix the confide_admindomain typo in the commit message.

Sure, now It should be ok. :)

2022-02-04 11:36 UTC, zpytela commented
Merging now, thank you.

2022-02-04 11:36 UTC, merged