New policy for insight-client
fedora-selinux/selinux-policy pull request #1056
Opened 2022-02-08 12:37 UTC by 5umm3r15

2022-02-08 21:03 UTC, zpytela requested changes
Additionally, please use tabs instead of spaces to indent.

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.fc
> +/etc/insights-client/[^/]*		--	gen_context(system_u:object_r:insights_client_etc_t,s0)
Possibly '+' can be used instead of '*'

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.fc
> +/var/lib/insights/newest\.egg(/.*)?	--	gen_context(system_u:object_r:insights_client_var_lib_t,s0)
This won't work - `--` matches plain files only.

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.fc
> +/var/log/insights-client(/.*)?		--	gen_context(system_u:object_r:insights_client_var_log_t,s0)
Same here.

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +files_read_etc_files(insights_client_t)
Why is this needed?

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +gpg_manage_home_content(insights_client_t)
gpg interfaces should be in an optional block

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +rhsmcertd_read_config_files(insights_client_t)
rhsmcertd interface should be in an optional block

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +logging_log_filetrans(insights_client_t, insights_client_var_log_t, { file dir })
Both file and dir are needed? Anyway dir file would be better.
And if the log dir is packaged, it will be labeled on the package install.

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +files_etc_filetrans(insights_client_t, insights_client_etc_t, { dir file })
Both file and dir are needed for filetrans?
Does insights client need to write to only some of etc files? It'd be better to indicate with the type like `...etc_rw_t`.

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +files_tmp_filetrans(insights_client_t, insights_client_tmp_t, { dir file })
Both file and dir are needed for filetrans?

2022-02-08 21:03 UTC, zpytela commented on policy/modules/contrib/insights_client.te
> +files_var_lib_filetrans(insights_client_t, insights_client_var_lib_t, { dir file })
Both file and dir are needed for filetrans? Isn't the lib dir packaged? In that case it would be labeled on the package install.

2022-02-09 12:44 UTC, 5umm3r15 commented on policy/modules/contrib/insights_client.te
> +files_read_etc_files(insights_client_t)
thanks, it is not needed, I removed it

2022-02-09 13:24 UTC, 5umm3r15 commented on policy/modules/contrib/insights_client.te
> +logging_log_filetrans(insights_client_t, insights_client_var_log_t, { file dir })
thanks, I removed file from it

2022-02-09 13:26 UTC, 5umm3r15 commented on policy/modules/contrib/insights_client.te
> +files_etc_filetrans(insights_client_t, insights_client_etc_t, { dir file })
I created etc_rw_t for certain files.

2022-02-09 13:28 UTC, 5umm3r15 commented on policy/modules/contrib/insights_client.te
> +files_var_lib_filetrans(insights_client_t, insights_client_var_lib_t, { dir file })
thanks, fixed

2022-02-09 13:29 UTC, 5umm3r15 commented on policy/modules/contrib/insights_client.te
> +files_tmp_filetrans(insights_client_t, insights_client_tmp_t, { dir file })
yes

2022-02-09 14:29 UTC, zpytela requested changes
If /var/lib/insights/ and /var/log/insights are a part of the package, they should be labelled properly at install time and there should be no need for manage_dirs_* and *_filetrans, in case of /var/lib also manage_files_*. It is different to transient files like those in /tmp and /run where it is needed.

2022-02-09 14:29 UTC, zpytela commented on policy/modules/contrib/insights_client.fc
> +/var/lib/insights/newest\.egg.asc			--	gen_context(system_u:object_r:insights_client_var_lib_t,s0)
One more dot to escape.

2022-02-09 14:29 UTC, zpytela commented on policy/modules/contrib/insights_client.if
> +    gen_require(`
Is it indented by spaces?

2022-02-09 14:29 UTC, zpytela commented on policy/modules/contrib/insights_client.fc
> +/var/log/insights-client(/.*)?					gen_context(system_u:object_r:insights_client_var_log_t,s0)
I also miss path entry in /var/run.

2022-02-09 21:48 UTC, 5umm3r15 commented
> If /var/lib/insights/ and /var/log/insights are a part of the package, they should be labelled properly at install time and there should be no need for manage_dirs_* and __filetrans, in case of /var/lib also manage_files__. It is different to transient files like those in /tmp and /run where it is needed.

Files are not a part of package but they are created.

2022-02-10 09:45 UTC, zpytela approved these changes

2022-02-10 09:46 UTC, zpytela commented
> > If /var/lib/insights/ and /var/log/insights are a part of the package, they should be labelled properly at install time and there should be no need for manage_dirs_* and **filetrans, in case of /var/lib also manage_files**. It is different to transient files like those in /tmp and /run where it is needed.
> 
> These files and dirs are not a part of package. They are created after a start of the service.

All right. I think this is not correct and we should report it, but it is needed now. So thank you for the contribution, I'll merge it so that it goes to the next build.

2022-02-11 10:42 UTC, merged