Add ksm service to ksmtuned
fedora-selinux/selinux-policy pull request #1178
Opened 2022-05-06 08:05 UTC by 5umm3r15

Add ksmctl and ksm.service - systemd service to start/stop
KSM (Kernel Samepage Merging) entirely.

Allow ksm to read/write sysfs files.

Fix BZ#2021131

2022-05-11 14:23 UTC, zpytela requested changes

2022-05-11 14:23 UTC, zpytela commented on policy/modules/contrib/ksmtuned.fc
> +/usr/lib/systemd/system/ksm.*		--	gen_context(system_u:object_r:ksm_unit_file_t,s0)
Please make it unambiguous, e. g. with `\..*` or full unit name `ksm\.service`, not to clash with the previous line.

2022-05-11 16:18 UTC, 5umm3r15 commented
@zpytela fixed, thanks

2022-05-13 16:17 UTC, zpytela approved these changes

2022-05-13 16:17 UTC, zpytela commented
Merging, thank you.

2022-05-13 16:17 UTC, merged