blueman-mechanism can read ~/.local/lib/python*/site-packages directory
fedora-selinux/selinux-policy pull request #1372
Opened 2022-09-07 08:07 UTC by milosmalik

If the ~/.local/lib/python*/site-packages/ directory exists in root's home directory then the blueman-mechanism service tries to read that directory during its start.

The blueman-mechanism program is written in Python and I believe that Python is trying to find locally installed python modules.

In order to avoid these SELinux denials, SELinux policy should allow the access.

Resolves: BZ#2027044

2022-09-14 07:53 UTC, zpytela commented
Please see the comments inline.

2022-09-14 07:54 UTC, zpytela requested changes

2022-09-14 07:54 UTC, zpytela commented on policy/modules/contrib/blueman.te
> +gnome_search_gconf_data_dir(blueman_t)
Looks this is a superset call of existing gnome_search_gconf(), so it can replace it. It anyway needs to be in an optional block (between 'd' and 'i' ones).

Also note this will resolve the problem only for non-root users, but I am fine with it.

2022-09-14 11:12 UTC, milosmalik commented
I updated the PR based on your feedback.

2022-09-14 11:33 UTC, zpytela approved these changes

2022-09-14 11:33 UTC, zpytela commented
Merging, thank you.

2022-09-14 11:33 UTC, merged

2022-09-25 15:09 UTC, wadebee commented
I am attempting to install a brand new instance of Fedora 36 and was immediately met with this warning upon initial login. Could you please provide instructions for how to properly apply this patch?