Add policy for nvme-stas
fedora-selinux/selinux-policy pull request #1565
Opened 2023-01-20 15:54 UTC by 5umm3r15

Add interface to allow domain to write the dbus pid sock_file.

Resolves: rhbz#2111414

2023-10-11 08:27 UTC, zpytela requested changes
Also an entry in modules.conf seems to be missing.

2023-10-11 08:27 UTC, zpytela commented on policy/modules/contrib/nvme_stas.if
> +
Seems to be an unnecessary blank line.

2023-10-11 08:27 UTC, zpytela commented on policy/modules/contrib/nvme_stas.te
> +nvme_stas_dbus_chat(nvme_stas_t)
This domain really needs dbus chat with itself?

2023-10-11 08:29 UTC, zpytela commented
Since the original bz has been closed migrated, I'd rather also have jira reference in the resolves field.

2023-10-11 14:27 UTC, 5umm3r15 commented
thanks for the review, fixed

2023-10-11 15:38 UTC, zpytela commented on policy/modules/contrib/nvme_stas.te
> +nvme_stas_dbus_chat(nvme_stas_t)
Interface from the same module should not be used unless there is a good reason; this time it seems just a simple allow rule is needed.

2023-10-17 18:57 UTC, zpytela commented
Merging, thank you.

2023-10-17 18:57 UTC, merged