Allow keepalived watch var_run dirs
fedora-selinux/selinux-policy pull request #1824
Opened 2023-08-08 16:05 UTC by 5umm3r15

Keepalived requires watch permission,
when keepalived tracked file is located in /var/run

Resolves: rhbz#2186759

2023-08-11 16:28 UTC, zpytela requested changes

2023-08-11 16:28 UTC, zpytela commented on policy/modules/contrib/keepalived.te
> +fs_getattr_ramfs(keepalived_t)
all ramfs elements have been changed to tmpfs

2023-08-11 16:28 UTC, zpytela commented on policy/modules/contrib/keepalived.te
> +files_watch_var_dirs(keepalived_t)
Should probably be files_watch_var_run_dirs()

2023-08-16 09:24 UTC, 5umm3r15 commented
fixed, thank you

2023-08-24 11:41 UTC, merged