WIP: Confine gnome-remote-desktop
fedora-selinux/selinux-policy pull request #2269
Opened 2024-07-26 13:43 UTC by bachradsusi

- add new gnome_remote_desktop_t port mapping for tcp 3389-3399
- add file type for /var/lib/gnome-remote-desktop(/.*)?
- add new domain and transition for /usr/libexec/gnome-remote-desktop-daemon

2024-08-27 15:33 UTC, zpytela requested changes
Please apply the suggested changes or reply back.

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.if
> +    tunable_policy(`deny_ptrace',`',`
Can you use tabs as separators here as well?

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +
I believe this whole block is a local module legacy.

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +optional_policy(`
optional blocks should be after allow rules from base

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +miscfiles_read_localization(gnome_remote_desktop_t)
miscfiles is a module

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +allow gnome_remote_desktop_t self:tcp_socket { accept bind create getattr getopt listen read setopt write };
better use create_stream_socket_perms

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +allow system_dbusd_t gnome_remote_desktop_t:tcp_socket { read write };
perhaps a room for using an interface? there are many other _rw_tcp_sockets()

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +kerberos_read_config(gnome_remote_desktop_t)
kerberos is a module

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +miscfiles_read_certs(gnome_remote_desktop_t)
one more miscfiles module

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +kernel_dgram_send(gnome_remote_desktop_t)
kernel does not obey to alphabetical order and is the first one

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +systemd_read_logind_sessions_files(gnome_remote_desktop_t)
systemd is a module

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +	xserver_dbus_chat_xdm(xdm_t)
is xdm_t to xdm_t dbus chat needed?

2024-08-27 15:33 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +')
rules for xdm should rather go to xserver module, just one more interface will be needed

2024-09-05 11:01 UTC, bachradsusi commented
@zpytela PTAL

I'll merge all the commits into one when you say it's ready to be merged.

2024-09-06 19:29 UTC, zpytela reviewed
I am fine with squashing.

2024-09-06 19:29 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +	type gnome_remote_desktop_port_t;
This should not be needed. The build may have failed just because of #L38.

2024-09-06 19:29 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +allow gnome_remote_desktop_t gnome_remote_desktop_port_t:tcp_socket name_bind;
The port type is not defined in this module, so interface should be used.

2024-09-06 19:29 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +allow gnome_remote_desktop_t self:unix_dgram_socket { create write };
Block of these allows should be at #L28.

2024-09-06 19:29 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +	allow system_dbusd_t gnome_remote_desktop_t:tcp_socket { read write };
Rule for system_dbus_t should be in the dbus module.

2024-09-06 19:29 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +	allow xdm_t gnome_remote_desktop_t:tcp_socket { getattr getopt read setopt shutdown write };
Rule for xdm_t should be in the xserver module.

2024-09-06 19:29 UTC, zpytela commented on policy/users
> +gen_user(xguest_u, user, xguest_r, s0, s0)
This has been merged in another PR.

2024-09-09 14:22 UTC, bachradsusi commented
@zpytela PTAL

Please be more specific with other requirements. I'm kind of beginner in this and I need specific instructions.

2024-09-09 16:27 UTC, zpytela commented on policy/modules/contrib/dbus.te
> +	allow system_dbusd_t gnome_remote_desktop_t:tcp_socket { read write };
Please create a new interface and use it here, no declaration of types from outside this module would be needed then.

I haven't managed to find any good example elsewhere, so either we can use gnome_remote_desktop_rw_tcp_sockets() with rw_socket_perms and use it both for xdm_t and also here where only read and write are needed, or create another interface with an ugly name like gnome_remote_desktop_rwonly_tcp_sockets(). There are many _rw_tcp_sockets() interfaces, some of them use just "read write", some rw_socket_perms.

2024-09-09 16:27 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +kernel_dgram_send(gnome_remote_desktop_t)
Seems the 39e1762614 and 2495d43ebb crossed somehow or my hint was not clear enough: kernel should be before other interfaces from base.

2024-09-09 16:27 UTC, zpytela commented on policy/modules/contrib/gnome_remote_desktop.te
> +logging_write_syslog_pid_socket(gnome_remote_desktop_t)
Logging should be in an optional block.

2024-09-09 16:27 UTC, zpytela commented on policy/modules/services/xserver.te
> +	xserver_read_xdm_state(gnome_remote_desktop_t)
These two xserver_ calls should be in g_r_d.te in an optional block

2024-09-10 07:18 UTC, bachradsusi commented
@zpytela another round, PTAL

2024-09-11 13:23 UTC, zpytela approved these changes

2024-09-11 13:23 UTC, zpytela commented
Merging, thank you.

2024-09-11 13:23 UTC, merged

2024-09-11 14:44 UTC, XhmikosR commented
Thanks @bachradsusi and @zpytela for your work!

Do you plan to backport this patch to Fedora 40? I'm asking because it's supposed to fix https://bugzilla.redhat.com/show_bug.cgi?id=2271661 and it's a pity that without this patch GRD doesn't work OOTB on Fedora stable.

2024-09-11 14:46 UTC, zpytela commented
F40 backport is considered.