Allow ipsec_mgmt_t read directories with ipsec_conf_file_t type BZ(17…
fedora-selinux/selinux-policy pull request #294
Opened 2019-11-18 14:36 UTC by zpytela

…73381)

2019-11-18 14:37 UTC, zpytela commented
The fix is not complete yet.

2019-11-25 16:19 UTC, zpytela commented
I decided to move the bug forward and propose a fix for both the parts. Please review, but consider the PR only for rawhide since the query on the strongswan maintainer is still in place.
```
# rpm -q selinux-policy; sesearch -A -s ipsec_mgmt_t -t ipsec_conf_file_t -c dir -p read; matchpathcon /usr/sbin/charon-systemd
selinux-policy-3.14.5-5.fc32.noarch
/usr/sbin/charon-systemd        system_u:object_r:bin_t:s0
# rpm -Fvh selinux-policy-*
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:selinux-policy-3.14.5-16.200.bz17################################# [ 25%]
   2:selinux-policy-targeted-3.14.5-16################################# [ 50%]
Cleaning up / removing...
   3:selinux-policy-targeted-3.14.5-5.################################# [ 75%]
   4:selinux-policy-3.14.5-5.fc32     ################################# [100%]
# rpm -q selinux-policy; sesearch -A -s ipsec_mgmt_t -t ipsec_conf_file_t -c dir -p read; matchpathcon /usr/sbin/charon-systemd
selinux-policy-3.14.5-16.200.bz1773381.fc32.noarch
allow ipsec_mgmt_t ipsec_conf_file_t:dir read;
/usr/sbin/charon-systemd        system_u:object_r:ipsec_mgmt_exec_t:s0
```

2019-11-25 17:26 UTC, wrabcak requested changes

2019-11-25 17:26 UTC, wrabcak commented on policy/modules/system/ipsec.te
> +allow ipsec_mgmt_t ipsec_conf_file_t:dir read;
Why there is no permission set like "list_dir_perms" ?

2019-11-25 18:05 UTC, mzabaluev commented
Responded in https://bugzilla.redhat.com/show_bug.cgi?id=1773381
I agree with the proposed fix as far as I can understand SELinux policies. charon-systemd is a more modern binary to run strongswan as a native systemd service, so it needs the same context as the rest of the family. Don't know enough about the intricacies of directory permissions.

2019-11-26 13:49 UTC, wrabcak commented
Thanks @zpytela for PR and @mzabaluev for review. Merging.

2019-11-26 13:49 UTC, merged