Create files_create_non_security_dirs() interface
fedora-selinux/selinux-policy pull request #305
Opened 2019-12-17 16:13 UTC by zpytela

2019-12-17 17:42 UTC, wrabcak commented
LGTM

2019-12-17 20:23 UTC, wrabcak requested changes

2019-12-17 20:23 UTC, wrabcak commented on policy/modules/kernel/files.if
> +
This is not needed here.

2019-12-18 07:30 UTC, zpytela commented
Extra line deleted.

2020-01-03 16:16 UTC, merged