Add 2 addl. interfaces to lvm
fedora-selinux/selinux-policy pull request #431
Opened 2020-09-16 19:03 UTC by tasleson

We need interfaces to allow applications the ability to:
* Update the lvm hints file
* Send dbus messages

This is needed for targetd storage daemon.

Signed-off-by: Tony Asleson <tasleson@redhat.com>

2020-09-18 13:02 UTC, zpytela requested changes

2020-09-18 13:02 UTC, zpytela commented on policy/modules/system/lvm.if
> +    allow $1 lvm_t:dbus send_msg;
The dbus communication usually needs to be allowed for both directions, it's not this case?

2020-09-18 13:02 UTC, zpytela commented on policy/modules/system/lvm.if
> +interface(`lvm_hints_file_access',`
To have it aligned with other interfaces names, it should rather be lvm_read_var_run

2020-09-18 13:02 UTC, zpytela commented on policy/modules/system/lvm.if
> +		class file { getattr read write open lock };
Class and permissions do not need to be declared in policy.

2020-09-18 13:02 UTC, zpytela commented on policy/modules/system/lvm.if
> +    allow $1 lvm_var_run_t:file { getattr read write open lock };
it's better to use permissions sets, or even file patterns.

2020-09-18 13:02 UTC, zpytela commented on policy/modules/system/lvm.if
> +interface(`lvm_hints_file_access',`
As there also is the write permission, it should actually rather be rw than read.

2020-09-18 17:05 UTC, tasleson commented on policy/modules/system/lvm.if
> +    allow $1 lvm_t:dbus send_msg;
In this specific case, we only need one direction as there is no reply.

2020-09-18 17:07 UTC, tasleson commented on policy/modules/system/lvm.if
> +    allow $1 lvm_var_run_t:file { getattr read write open lock };
Done: converted to use permission sets.

2020-09-18 17:07 UTC, tasleson commented on policy/modules/system/lvm.if
> +		class file { getattr read write open lock };
Done, removed.

2020-09-18 17:07 UTC, tasleson commented on policy/modules/system/lvm.if
> +interface(`lvm_hints_file_access',`
Done

2020-09-18 20:34 UTC, zpytela commented on policy/modules/system/lvm.if
> +    allow $1 lvm_var_run_t:file { getattr read write open lock };
Note there are `rw_file_perms`; unfortunately, there is no `rw_files_pattern` which ensures the domain can access the parent directory.

2020-09-18 20:40 UTC, zpytela commented
Please adjust the commit message in this PR, too. The interfaces names will fit into the first line, and optionally the content of comment#1 can be in the body.

2020-09-18 21:10 UTC, tasleson commented on policy/modules/system/lvm.if
> +    allow $1 lvm_var_run_t:file { getattr read write open lock };
Changed to `rw_file_perms`

2020-09-18 21:10 UTC, tasleson commented
> Please adjust the commit message in this PR, too. The interfaces names will fit into the first line, and optionally the content of comment#1 can be in the body.

Done

2020-09-21 11:52 UTC, wrabcak commented
LGTM.

2020-09-21 13:25 UTC, zpytela commented
Thanks, merging to rawhide, please let me know if backport to any other fedora is required.

2020-09-21 13:25 UTC, merged

2020-09-21 13:27 UTC, tasleson commented
> Thanks, merging to rawhide, please let me know if backport to any other fedora is required.

Please, merge these changes into F33 & F32, thanks!

2020-09-21 13:41 UTC, zpytela commented
Done, will merge them when ci finishes.
https://github.com/fedora-selinux/selinux-policy/pull/442
https://github.com/fedora-selinux/selinux-policy/pull/443