Adds rule to allow glusterd to access RDMA socket
fedora-selinux/selinux-policy pull request #496
Opened 2020-12-07 09:38 UTC by lveyde

Resolves: rhbz#1779052

Signed-off-by: Lev Veyde <lveyde@redhat.com>

2020-12-07 09:42 UTC, lveyde commented
@wrabcak @rhatdan

2020-12-07 13:27 UTC, zpytela requested changes
@lveyde, do you have any test using this socket type?

2020-12-07 13:27 UTC, zpytela commented on policy/modules/contrib/glusterd.te
> +allow glusterd_t self:netlink_rdma_socket { bind create setopt };
Please use one of the macros available for socket permissions in https://github.com/fedora-selinux/selinux-policy/blob/rawhide/policy/support/obj_perm_sets.spt

2020-12-07 17:41 UTC, zpytela commented
@lveyde please also ensure the same commit goes to the glusterfs-selinux package as the gluster team manages their own policy. I actually expect all future development happens only there.

2020-12-07 17:44 UTC, wrabcak commented
@zpytela, Can you provide the link for the gluster-selinux repo, so all parties are on same page where the commit should go?

2020-12-07 17:46 UTC, zpytela commented
https://github.com/gluster/glusterfs-selinux/

2021-01-25 15:35 UTC, WOnder93 approved these changes

2021-01-25 18:56 UTC, zpytela approved these changes

2021-01-25 18:57 UTC, zpytela commented
Thank you for the PR; consider cherry-picking to https://github.com/gluster/glusterfs-selinux/

2021-01-25 18:57 UTC, merged