Allow additional rules for use opencryptoki
fedora-selinux/selinux-policy pull request #637
Opened 2021-03-08 08:59 UTC by Koncpa

Certmonger and Ipsec need more permission for proper usage of opencryptoki.
Add private label pkcs_slotd_tmpfs_t for /dev/shm/var.lib.opencryptoki files. Create new
interface pkcs_tmpfs_filetrans(), which allow file transition to
var.lib.opencryptoki files. Also interface allow manage this files and
manage tmpfs dirs. Use this interface for ipsec and certmonger services.
Add to interface pkcs_use_opencryptoki corenet_tcp_connect_tcs_port(),
which allow connect to tcs port for domains which use opencryptoki.
Add chown capability for ipsec domain and
allow get the attributes of a tmpfs for certmonger.

COPR build: https://download.copr.fedorainfracloud.org/results/pkoncity/selinux-policy/fedora-rawhide-x86_64/02052708-selinux-policy/
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1894132

2021-04-07 18:00 UTC, WOnder93 commented
I think it would be better to use a named transition specifically for `var.lib.opencryptoki.tpm.root`, otherwise this could result in files e.g. in `/tmp` to get an unexpected label. Hopefully the services won't run as non-root in the near future, at least until I implement prefix/suffix-based filename transitions :)

Also, it would be nicer to split this into multiple commits (I would separate out at least the capability addition and the corenet_tcp_connect_tcs_port() call).

And please don;t forget to double-check the whitespace consistency in your patches ;P

2021-05-04 11:23 UTC, zpytela commented
The content looks good, I'd suggest escape dots in the file context specification, and use tabs for indentation in the new interface.
Consider splitting the commit and add reasons for the new permissions when they are available.
Please also change the commit message to make it more clear and comprehensible.

2021-05-04 11:24 UTC, zpytela commented
> I think it would be better to use a named transition specifically for `var.lib.opencryptoki.tpm.root`, otherwise this could result in files e.g. in `/tmp` to get an unexpected label. Hopefully the services won't run as non-root in the near future, at least until I implement prefix/suffix-based filename transitions :)

This is a transition for `/dev/shm` with the `tmpfs_t` type, so why are you worried about `/tmp`?

2021-05-27 19:01 UTC, zpytela requested changes

2021-05-27 19:01 UTC, zpytela commented on policy/modules/contrib/pkcs.if
> +        type pkcs_slotd_tmpfs_t;
Please replace 8 spaces with 2 tabs.

2021-05-27 19:05 UTC, zpytela commented
Last two requests:
- split the "ipsec and certmonger" commit into two to ease backporting
- add a bugzilla reference to each commit

2021-06-03 18:14 UTC, zpytela commented
LGTM now, thank you.

2021-06-03 18:14 UTC, merged