Allow rhsmcertd to create cache file in /var/cache/cloud-what
fedora-selinux/selinux-policy pull request #836
Opened 2021-08-17 16:29 UTC by jirihnidek

* The `rhsmcertd` uses new python package cloud-what. This
  package tries to create cache file in `/var/cache/cloud-what`
* This commit create new label `cloud_what_var_cache_t` for this
  directory and it allows `rhsmcertd` service to manage files and
  directories in this cache directory.

2021-08-18 07:51 UTC, jirihnidek commented
More details about this issue could be found here: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c6

2021-08-24 18:27 UTC, zpytela requested changes

2021-08-24 18:27 UTC, zpytela commented on policy/modules/contrib/rhsmcertd.if
> +	files_search_var_lib($1)
The purpose of a line like this in the interface is to allow access to the type of the parent directory. In this case it is var_t, so `files_search_var($1)` should be used instead.
Same for the next interface.
```
# ls -lZd /var/cache /var/cache/httpd
drwxr-xr-x. 1 root   root   system_u:object_r:var_t:s0         238 Jul 16 15:02 /var/cache
drwx------. 1 apache apache system_u:object_r:httpd_cache_t:s0  10 Jun  2 14:08 /var/cache/httpd
```

2021-08-25 10:33 UTC, zpytela commented
Merging, thank you.

2021-08-25 10:33 UTC, merged