Allow braille printing (cups-brf) in selinux
fedora-selinux/selinux-policy pull request #849
Opened 2021-08-25 12:19 UTC by zdohnal

cups-brf gets data from getpwnam() to switch itself to the user who
issued the print job and then creates BRF dir and output files in user
home directories (/home/<username>/BRF for regular user, /root/BRF for
root).

2021-08-25 12:24 UTC, sthibaul commented
(this is very much like cups-pdf)

2021-08-27 09:15 UTC, zpytela requested changes

2021-08-27 09:15 UTC, zpytela commented on policy/modules/contrib/cups.te
> +allow cups_brf_t self:capability dac_override;
Can you share some details? What happens on the filesystem when printing as root?

2021-08-27 09:15 UTC, zpytela commented on policy/modules/contrib/cups.te
> +sssd_search_lib(cups_brf_t)
sssd is a module, its interfaces calls should be in an optional block.
authlogin, init, userdomain actually are modules, too, but they hardly can be removed from the system, so it's better to leave them where they are.

2021-08-31 08:59 UTC, zdohnal commented on policy/modules/contrib/cups.te
> +allow cups_brf_t self:capability dac_override;
cups-brf backend calls getpwnam() to get info about the user who started print job and then the backend sets UID and GID to match with the issuer.
Then the backend uses umask() to 'act as the user' by forbidding permissions for 'group' and 'other' classes and creates BRF directory in user home directory (```/root``` for root user), creates a file in it, write filters' output in it and closes it.

To be honest, this is my first time writing a selinux policy, so I followed the suggestions from ```audit2allow``` command after I'd got a selinux denial, so I was updating the policy until the print job passed. Do feel free to let me know if I should approach this differently.

2021-08-31 09:00 UTC, zdohnal commented on policy/modules/contrib/cups.te
> +sssd_search_lib(cups_brf_t)
@zpytela do you mean like this:

```
optional_policy(`
  sssd_search_lib(cups_brf_t)
')
```

?

2021-10-13 10:27 UTC, zdohnal commented
@zpytela ping questions in review

2021-10-13 11:32 UTC, zpytela commented on policy/modules/contrib/cups.te
> +sssd_search_lib(cups_brf_t)
Yes, just move it down (L621 or so).

2021-10-13 11:33 UTC, zpytela commented on policy/modules/contrib/cups.te
> +allow cups_brf_t self:capability dac_override;
Please also update the commit message with the information for future reference.

2021-10-13 11:33 UTC, zpytela commented
> @zpytela ping questions in review

I am sorry, I completely missed the notifications.

2021-10-14 05:33 UTC, zdohnal commented on policy/modules/contrib/cups.te
> +sssd_search_lib(cups_brf_t)
Moved down.

2021-10-14 05:34 UTC, zdohnal commented on policy/modules/contrib/cups.te
> +allow cups_brf_t self:capability dac_override;
The commit message was updated to:

```
   Allow braille printing in selinux

    Description of the process:

    cups-brf backend calls getpwnam() to get info about the user who started
    print job and then the backend sets its UID and GID to match with the
    issuer.
    After that the backend uses umask() to 'act as the user' by forbidding
    permissions for 'group' and 'other' classes and creates BRF directory in
    user home directory (/root for root user, /home/<username> for others),
    creates a file in the directory, write filters' output in the file
    and closes it.
```

2021-10-21 06:18 UTC, zdohnal commented
@zpytela updated, would you mind looking into the current PR?

2021-10-26 17:39 UTC, zpytela commented
The commit well matches cups-pdf so as such it is fine. However, there is one troublesome thing: with `userdom_manage_user_home_content_dirs(cups_brf_t)` we are giving to the plugin unnecessary permissions to manage user's home.

Will it be possible to change the software behaviour to use some XDG adviced directory, e. g. ~/.config/cups/brf?

2021-10-27 08:54 UTC, zdohnal commented
> Will it be possible to change the software behaviour to use some XDG adviced directory, e. g. ~/.config/cups/brf?

@zpytela  The file in the created BRF dir is a printout of a document - IMHO it doesn't make much sense to put it into a dir which is meant for configurations...

Is it possible to somehow define in selinux policy that the backend can only create and access only BRF directory in home dir, and then open/write/close files in BRF dir?

2021-10-27 09:00 UTC, zpytela commented
> > Will it be possible to change the software behaviour to use some XDG adviced directory, e. g. ~/.config/cups/brf?
> 
> @zpytela The file in the created BRF dir is a printout of a document - IMHO it doesn't make much sense to put it into a dir which is meant for configurations...

What I meant was ~/.cache, but there are other "well-known" directories, too.

> 
> Is it possible to somehow define in selinux policy that the backend can only create and access only BRF directory in home dir, and then open/write/close files in BRF dir?

Policy can give access to a particular directory, but if it does not exist, permissions to modify user's home dir are required if it is in user's home dir. That's why a dedicated data/cache/runtime directory is a better choice.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

2021-10-27 09:05 UTC, zdohnal commented
@sthibaul Hi Sam,

as cups-brf author, would you mind looking into the proposal @zpytela mentioned? Is it acceptable to change the dir?

2021-10-27 15:02 UTC, sthibaul commented
> Is it acceptable to change the dir?

Well, as much as it would be for the cups-pdf filter. The problem is that if the file is stuffed into a hidden directory, there is very little probability that the user will find it...

2021-11-01 09:59 UTC, zdohnal commented
@zpytela ,

based on @sthibaul review, the changing of dir would reduce the output visibility, so cups-brf cannot use a XDG dir for output.

2021-11-05 16:42 UTC, zpytela commented
I see. This needs to be discussed in our team, I'll let you know.

2021-12-06 13:12 UTC, zdohnal commented
Hi @zpytela ,

any news regarding the PR?

2021-12-22 20:10 UTC, zpytela commented
It is still considered unfortunate and we will appreciate using a standardized directory in the future in order not to allow arbitrary domains manage user's home. Merging though as the risk has been assessed minimal. Thank you for your contribution.

2021-12-22 20:10 UTC, merged