Multiple commits which allow proper function soreport in sysadmin role
fedora-selinux/selinux-policy pull request #894
Opened 2021-09-23 08:39 UTC by Koncpa

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1965251

2021-10-15 14:14 UTC, zpytela requested changes
Also please change "sysadm domain" to "sysadm_t domain" in one of the commit messages.

2021-10-15 14:14 UTC, zpytela commented on policy/modules/contrib/iotop.te
> +allow iotop_t self:netlink_generic_socket { bind create getattr setopt };
Please use object permissions sets when they are available, like `create_socket_perms`.

2021-10-15 14:14 UTC, zpytela commented on policy/modules/contrib/iotop.te
> +allow iotop_t self:unix_dgram_socket { create getopt setopt } ;
Same here.

2021-10-15 16:40 UTC, Koncpa commented on policy/modules/contrib/iotop.te
> +allow iotop_t self:netlink_generic_socket { bind create getattr setopt };
DONE

2021-10-15 16:40 UTC, Koncpa commented on policy/modules/contrib/iotop.te
> +allow iotop_t self:unix_dgram_socket { create getopt setopt } ;
DONE

2021-10-18 08:01 UTC, zpytela commented
Merging, thank you.

2021-10-18 08:01 UTC, zpytela approved these changes

2021-10-18 08:01 UTC, merged