Document Security Flask model in the policy
fedora-selinux/selinux-policy pull request #901
Opened 2021-09-30 12:33 UTC by 5umm3r15

Created markdown file flask_documentation.md,
where are documented selinux-policy
permissions and classes.

2021-10-06 11:00 UTC, vmojzis requested changes
Looks really good.
I only noted a few typos/readability improvements.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**execmod** - Make executable a file mapping that has been modified by copy-on-write. (Text relocation)
Execute memory-mapped files that *have been modified* in the process memory. This permission check is useful in keeping shared libraries from being modified within a process.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**watch\_with\_perm** - "Only applies to fanotify masks since it is the only way to set a mask which
Set a watch for fanotify "permission events" (blocking events that make a request to the receiving application whether or not given action may be completed).

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**database** - he common database permissions that are inherited by a number of object classes
he common -> The common

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**relabelfrom** - Relabel from old security context.
Change the security context based on the new type.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**relabelto** - Relabel to new security context.
Change the security context based on the new type.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**read** - Read from socket.
There is probably no need to describe inherited permissions since they where already described (in this case in "file" class).

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**sys\_chroot** - Grant use of the chroot(2) call.
Allow use of the chroot(2) call.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**sys\_nice** - Grants privilege to change priority of any process. Grants change of scheduling algorithm used by any process.
Grants privilege to change priority of any process, or scheduling algorithm used by any process.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**mknod** - Grants permission to creation of character and block device nodes.
Allows creation of character and block device nodes.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**open** - Open a block device file.
This is inherited from file - should be removed (especially since it's not the only inherited permission)

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**open** - Open a named socket file
This is inherited from file

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**open** - Open a FIFO.
This is inherited from file

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**enforce\_dest** - Ensure that the destination node can enforce restrictions on the destination socket.
Never used in mainline Linux.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +Netlink socket that is not part of any specificSELinux Netlink socket class. Protocol: PF\_NETLINK Family Type:All other types that are not part of any other specific netlink object class.
specificSELinux -> specific SELinux

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**validate\_trans** - Validate a transition. (This determines whether a transition from scone to newcon using tcon as the target for object class tclass is valid in the loaded policy)
scone -> scon
Also, we might want to highlight (e.g. use italics) "scon", "tcon" and "tclass" to make this more readable.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +This is the overall system object and there is only oneinstance of this object.
oneinstance -> one instance

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**show** -
Show a drawable object.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**getattr** - Get attributes from a specific screen..
Duplicate full stop.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +Manage some X-server events (e.g.confignotify). Note the x\_event permissions will still be required (its magic).
It's magic :D :D

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +Supports 'secmark' services where packets are labeledusing iptables to select and label packets, SELinux thent enforcespolicy using these packet labels.
labeledusing -> labeled using

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**relabelfrom** - Relabel from old security context.
Change the security context based on the new type.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**relabelto** - Relabel to new security context.
Change the security context based on the new type.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**execmod** - Make executable a file mapping that has been modified by copy-on-write. (Text relocation)
Execute memory-mapped files that have been modified in the process memory. This permission check is useful in keeping shared libraries from being modified within a process.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**watch\_with\_perm** - Only applies to fanotify masks since it is the only way to set a mask which allows for the blocking event.
Set a watch for fanotify "permission events" (blocking events that make a request to the receiving application whether or not given action may be completed).

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**read** - Read from socket.
There is probably no need to describe inherited permissions since they where already described (in this case in "file" class).

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**sys\_chroot** - Grant use of the chroot(2) call.
Allow use of the chroot(2) call.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**sys\_nice** - Grants privilege to change priority of any process. Grants change of scheduling algorithm used by any process.
Grants privilege to change priority of any process, or scheduling algorithm used by any process.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**mknod** - Grants permission to creation of character and block device nodes.
Allows creation of character and block device nodes.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**validate\_trans** - Validate a transition. (This determines whether a transition from scone to newcon using tcon as the target for object class tclass is valid in the loaded policy.)
scone -> scon
Also, we might want to highlight (e.g. use italics) "scon", "tcon" and "tclass" to make this more readable.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**show**
Show a drawable object.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**getattr** - Get attributes from a specific screen..
Duplicate full stop.

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +Manage some X-server events (e.g.config notify). Note the x\_event permissions will still be required (its magic).
its magic -> It's magic
:D :D

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +This is a userspace object for the translation daemonmcstransd. These permissions are required to allow translation and querying of level and ranges for MCS and MLS systems.
daemonmcstransd -> daemon mcstransd

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**import** - Import a file as a binary large object by calling thelo\_import()function.
thelo\_import()function -> the lo\_import()function

2021-10-06 11:00 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**implement** - Whether the language can be implemented or not for the SQL procedure.
Checked when a procedure is constructed on this procedural language.

2021-10-21 08:10 UTC, vmojzis approved these changes

2021-10-26 16:13 UTC, zpytela requested changes
Two additional patterns:
- full stop not followed by a space
- X windows should be X window

Will it also be possible/easy to make a (very brief) list of content and separate the blocks visually (horizontal line or so) for a quick orientation?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**map**
Description missing, e. g.

Allow a file to be memory mapped via mmap(2).

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +*inherited from file*
Does it really apply here?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**add**
Many entries here miss description or an "Unused" note.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**getattr** - Get file attributes, such as access mode. (e.g. stat, some ioctls. ...)
I cannot find any direct reference, but I think this is not correct.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**reparent** - Rename into a different parent directory (.. change).
A typo?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +*Extended Netlink classes*
Was this meant to be a heading?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**nlmsg\_read** - Read firewall configuration state.
This should probably read `Read/Write kernel routing table`.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +*The remaining network socket classes were previously # mapped to the socket class and therefore have the # same definition as socket.*
Don't quite understand: This is a note regarding the following classes?
Anyway, a hash sign should not be here.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**getattr** - Get attributes of a file.
Is this really a file attribute?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**getpgid** - Get group Process ID of a process.
Should be said explicitly 'another' process, see getsession.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**getsched** - Get priority of a process.
Is this also another process?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**setenforce # was avc\_toggle in system class** - Change the enforcement state of SELinux.
A comment to delete.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**stop** - Stop system.
Can you point me to your resources for start/stop/status?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**syslog\_console** - Perform syslog console.
I don't understand.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**dac\_override** - Override all DAC access restrictions. Checked before dac\_read\_search, so a dontaudit candidate.
I think the order changed some time ago.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**setuid** - Allow set*uid(2). Allow passing of forged ids on credentials passed over a socket.
Is it possible to get rid of the asterisk, e. g. with enumerating the syscalls?

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**sys\_resource** - Override the following: resource limits; quota limits; reserved space onext2 filesystem; size restrictions on IPC message queues; max number of consoles on console allocation; max
Typo onext2. The comma should be a full stop.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**list\_property** - List property associated with a window. Normally SystemLow for MLSsystems.
Typo MLSsystems

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**relabelto**
Description missing.

2021-10-26 16:13 UTC, zpytela commented on policy/flask/flask_documentation.md
> +## class xdp\_socket
I'd rather see this socket next to other sockets.

2021-10-27 13:13 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +**reparent** - Rename into a different parent directory (.. change).
What do you mean?
".. change" is correct - parent directory changes

2021-10-27 13:16 UTC, zpytela commented on policy/flask/flask_documentation.md
> +**reparent** - Rename into a different parent directory (.. change).
I did not understand the .. meaning. So it's not a typo, but still unclear at the first read.

2021-10-27 13:19 UTC, vmojzis commented on policy/flask/flask_documentation.md
> +*The remaining network socket classes were previously # mapped to the socket class and therefore have the # same definition as socket.*
Agreed, comments like this should probably be removed, since they are dependent on the class order in the original document, which was not preserved here.

2021-11-03 12:40 UTC, 5umm3r15 commented on policy/flask/flask_documentation.md
> +**stop** - Stop system.
Definition of status is available in [The SELinux Notebook - class system](https://freecomputerbooks.com/books/The_SELinux_Notebook-4th_Edition.pdf#page=361)

No resources for start and stop.

2021-11-03 12:41 UTC, 5umm3r15 commented on policy/flask/flask_documentation.md
> +**map**
Thanks!

2021-12-10 17:12 UTC, zpytela approved these changes

2021-12-10 17:12 UTC, zpytela commented
Merging, thank you for your effort.

2021-12-10 18:12 UTC, merged